-- Clear existing problems and reset sequence
TRUNCATE problems RESTART IDENTITY CASCADE;

INSERT INTO problems (title, topic, difficulty, platform_link, companies, prerequisite_topic) VALUES

-- ============================================================
-- ARRAYS (60 problems)
-- ============================================================
('Two Sum', 'Arrays', 'Easy', 'https://leetcode.com/problems/two-sum/', ARRAY['Google','Amazon','Facebook','Apple','Microsoft'], 'Arrays'),
('Best Time to Buy and Sell Stock', 'Arrays', 'Easy', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', ARRAY['Amazon','Facebook','Microsoft'], 'Arrays'),
('Contains Duplicate', 'Arrays', 'Easy', 'https://leetcode.com/problems/contains-duplicate/', ARRAY['Amazon','Apple','Google'], 'Arrays'),
('Maximum Subarray', 'Arrays', 'Medium', 'https://leetcode.com/problems/maximum-subarray/', ARRAY['Amazon','Apple','Microsoft','Google'], 'Arrays'),
('Product of Array Except Self', 'Arrays', 'Medium', 'https://leetcode.com/problems/product-of-array-except-self/', ARRAY['Amazon','Facebook','Microsoft','Google'], 'Arrays'),
('Maximum Product Subarray', 'Arrays', 'Medium', 'https://leetcode.com/problems/maximum-product-subarray/', ARRAY['Amazon','Google','Microsoft'], 'Arrays'),
('Find Minimum in Rotated Sorted Array', 'Arrays', 'Medium', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', ARRAY['Amazon','Microsoft','Google'], 'Binary Search'),
('Search in Rotated Sorted Array', 'Arrays', 'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', ARRAY['Amazon','Facebook','Microsoft','Google'], 'Binary Search'),
('3Sum', 'Arrays', 'Medium', 'https://leetcode.com/problems/3sum/', ARRAY['Amazon','Facebook','Microsoft','Google'], 'Two Pointers'),
('Container With Most Water', 'Arrays', 'Medium', 'https://leetcode.com/problems/container-with-most-water/', ARRAY['Amazon','Facebook','Google'], 'Two Pointers'),
('Trapping Rain Water', 'Arrays', 'Hard', 'https://leetcode.com/problems/trapping-rain-water/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Two Pointers'),
('Merge Intervals', 'Arrays', 'Medium', 'https://leetcode.com/problems/merge-intervals/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Sorting'),
('Insert Interval', 'Arrays', 'Medium', 'https://leetcode.com/problems/insert-interval/', ARRAY['Google','Facebook'], 'Sorting'),
('Non-overlapping Intervals', 'Arrays', 'Medium', 'https://leetcode.com/problems/non-overlapping-intervals/', ARRAY['Google'], 'Greedy'),
('Meeting Rooms', 'Arrays', 'Easy', 'https://leetcode.com/problems/meeting-rooms/', ARRAY['Facebook','Amazon'], 'Sorting'),
('Meeting Rooms II', 'Arrays', 'Medium', 'https://leetcode.com/problems/meeting-rooms-ii/', ARRAY['Amazon','Facebook','Google'], 'Greedy'),
('Rotate Array', 'Arrays', 'Medium', 'https://leetcode.com/problems/rotate-array/', ARRAY['Microsoft','Amazon'], 'Arrays'),
('Move Zeroes', 'Arrays', 'Easy', 'https://leetcode.com/problems/move-zeroes/', ARRAY['Facebook','Amazon'], 'Two Pointers'),
('Find the Duplicate Number', 'Arrays', 'Medium', 'https://leetcode.com/problems/find-the-duplicate-number/', ARRAY['Amazon','Facebook'], 'Two Pointers'),
('Majority Element', 'Arrays', 'Easy', 'https://leetcode.com/problems/majority-element/', ARRAY['Amazon','Microsoft','Apple'], 'Arrays'),
('Sort Colors', 'Arrays', 'Medium', 'https://leetcode.com/problems/sort-colors/', ARRAY['Facebook','Microsoft'], 'Two Pointers'),
('Next Permutation', 'Arrays', 'Medium', 'https://leetcode.com/problems/next-permutation/', ARRAY['Amazon','Microsoft'], 'Arrays'),
('Jump Game', 'Arrays', 'Medium', 'https://leetcode.com/problems/jump-game/', ARRAY['Amazon','Microsoft'], 'Greedy'),
('Jump Game II', 'Arrays', 'Medium', 'https://leetcode.com/problems/jump-game-ii/', ARRAY['Amazon','Microsoft'], 'Greedy'),
('Gas Station', 'Arrays', 'Medium', 'https://leetcode.com/problems/gas-station/', ARRAY['Amazon'], 'Greedy'),
('Candy', 'Arrays', 'Hard', 'https://leetcode.com/problems/candy/', ARRAY['Amazon'], 'Greedy'),
('H-Index', 'Arrays', 'Medium', 'https://leetcode.com/problems/h-index/', ARRAY['Facebook'], 'Sorting'),
('Pascal Triangle', 'Arrays', 'Easy', 'https://leetcode.com/problems/pascals-triangle/', ARRAY['Amazon','Apple'], 'Arrays'),
('Spiral Matrix', 'Arrays', 'Medium', 'https://leetcode.com/problems/spiral-matrix/', ARRAY['Amazon','Microsoft','Google'], 'Arrays'),
('Set Matrix Zeroes', 'Arrays', 'Medium', 'https://leetcode.com/problems/set-matrix-zeroes/', ARRAY['Amazon','Microsoft'], 'Arrays'),
('Rotate Image', 'Arrays', 'Medium', 'https://leetcode.com/problems/rotate-image/', ARRAY['Amazon','Microsoft','Google'], 'Arrays'),
('Search a 2D Matrix', 'Arrays', 'Medium', 'https://leetcode.com/problems/search-a-2d-matrix/', ARRAY['Amazon','Microsoft'], 'Binary Search'),
('Kth Largest Element in an Array', 'Arrays', 'Medium', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', ARRAY['Amazon','Facebook','Microsoft'], 'Heap'),
('Top K Frequent Elements', 'Arrays', 'Medium', 'https://leetcode.com/problems/top-k-frequent-elements/', ARRAY['Amazon','Facebook','Google'], 'Heap'),
('Find K Closest Elements', 'Arrays', 'Medium', 'https://leetcode.com/problems/find-k-closest-elements/', ARRAY['Google','LinkedIn'], 'Binary Search'),
('Subarray Sum Equals K', 'Arrays', 'Medium', 'https://leetcode.com/problems/subarray-sum-equals-k/', ARRAY['Facebook','Google'], 'Hash Map'),
('Longest Consecutive Sequence', 'Arrays', 'Medium', 'https://leetcode.com/problems/longest-consecutive-sequence/', ARRAY['Google','Facebook'], 'Hash Map'),
('Two Sum II - Input Array Is Sorted', 'Arrays', 'Medium', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', ARRAY['Amazon'], 'Two Pointers'),
('4Sum', 'Arrays', 'Medium', 'https://leetcode.com/problems/4sum/', ARRAY['Amazon'], 'Two Pointers'),
('Remove Duplicates from Sorted Array', 'Arrays', 'Easy', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', ARRAY['Microsoft','Amazon'], 'Two Pointers'),
('Remove Element', 'Arrays', 'Easy', 'https://leetcode.com/problems/remove-element/', ARRAY['Amazon'], 'Two Pointers'),
('Plus One', 'Arrays', 'Easy', 'https://leetcode.com/problems/plus-one/', ARRAY['Google','Amazon'], 'Arrays'),
('Merge Sorted Array', 'Arrays', 'Easy', 'https://leetcode.com/problems/merge-sorted-array/', ARRAY['Facebook','Amazon','Microsoft'], 'Two Pointers'),
('Single Number', 'Arrays', 'Easy', 'https://leetcode.com/problems/single-number/', ARRAY['Amazon','Microsoft'], 'Bit Manipulation'),
('Missing Number', 'Arrays', 'Easy', 'https://leetcode.com/problems/missing-number/', ARRAY['Amazon','Microsoft'], 'Bit Manipulation'),
('Find All Numbers Disappeared in an Array', 'Arrays', 'Easy', 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/', ARRAY['Google'], 'Arrays'),
('Maximum Sum Circular Subarray', 'Arrays', 'Medium', 'https://leetcode.com/problems/maximum-sum-circular-subarray/', ARRAY['Amazon'], 'Dynamic Programming'),
('Minimum Size Subarray Sum', 'Arrays', 'Medium', 'https://leetcode.com/problems/minimum-size-subarray-sum/', ARRAY['Amazon','Microsoft'], 'Sliding Window'),
('Sliding Window Maximum', 'Arrays', 'Hard', 'https://leetcode.com/problems/sliding-window-maximum/', ARRAY['Amazon','Google'], 'Deque'),
('Count of Smaller Numbers After Self', 'Arrays', 'Hard', 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/', ARRAY['Google','Facebook'], 'Merge Sort'),
('First Missing Positive', 'Arrays', 'Hard', 'https://leetcode.com/problems/first-missing-positive/', ARRAY['Amazon'], 'Arrays'),
('Median of Two Sorted Arrays', 'Arrays', 'Hard', 'https://leetcode.com/problems/median-of-two-sorted-arrays/', ARRAY['Amazon','Google','Microsoft'], 'Binary Search'),
('Array Rotation', 'Arrays', 'Easy', 'https://www.geeksforgeeks.org/problems/rotate-array-by-n-elements-1587115621/1', ARRAY['TCS','Infosys'], 'Arrays'),
('Equilibrium Point', 'Arrays', 'Easy', 'https://www.geeksforgeeks.org/problems/equilibrium-point-1587115620/1', ARRAY['Amazon','Flipkart'], 'Arrays'),
('Leaders in an Array', 'Arrays', 'Easy', 'https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1', ARRAY['Amazon'], 'Arrays'),
('Minimum Platforms', 'Arrays', 'Medium', 'https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1', ARRAY['Amazon','Microsoft'], 'Greedy'),
('Stock Buy and Sell', 'Arrays', 'Easy', 'https://www.geeksforgeeks.org/problems/stock-buy-and-sell-1587115621/1', ARRAY['Amazon','Flipkart'], 'Greedy'),
('Count Inversions', 'Arrays', 'Medium', 'https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1', ARRAY['Amazon','Microsoft'], 'Merge Sort'),
('Kadane Algorithm', 'Arrays', 'Medium', 'https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1', ARRAY['Amazon','Google'], 'Dynamic Programming'),
('Chocolate Distribution Problem', 'Arrays', 'Easy', 'https://www.geeksforgeeks.org/problems/chocolate-distribution-problem3825/1', ARRAY['Amazon'], 'Sorting'),
('Trapping Rain Water GFG', 'Arrays', 'Hard', 'https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1', ARRAY['Amazon','Google'], 'Two Pointers'),

-- ============================================================
-- STRINGS (50 problems)
-- ============================================================
('Valid Anagram', 'Strings', 'Easy', 'https://leetcode.com/problems/valid-anagram/', ARRAY['Amazon','Facebook','Microsoft'], 'Strings'),
('Valid Palindrome', 'Strings', 'Easy', 'https://leetcode.com/problems/valid-palindrome/', ARRAY['Facebook','Microsoft'], 'Two Pointers'),
('Longest Substring Without Repeating Characters', 'Strings', 'Medium', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Sliding Window'),
('Longest Repeating Character Replacement', 'Strings', 'Medium', 'https://leetcode.com/problems/longest-repeating-character-replacement/', ARRAY['Google'], 'Sliding Window'),
('Minimum Window Substring', 'Strings', 'Hard', 'https://leetcode.com/problems/minimum-window-substring/', ARRAY['Amazon','Facebook','Google'], 'Sliding Window'),
('Group Anagrams', 'Strings', 'Medium', 'https://leetcode.com/problems/group-anagrams/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Hash Map'),
('Encode and Decode Strings', 'Strings', 'Medium', 'https://leetcode.com/problems/encode-and-decode-strings/', ARRAY['Google'], 'Strings'),
('Palindromic Substrings', 'Strings', 'Medium', 'https://leetcode.com/problems/palindromic-substrings/', ARRAY['Facebook','Amazon'], 'Dynamic Programming'),
('Longest Palindromic Substring', 'Strings', 'Medium', 'https://leetcode.com/problems/longest-palindromic-substring/', ARRAY['Amazon','Microsoft','Google'], 'Dynamic Programming'),
('String to Integer (atoi)', 'Strings', 'Medium', 'https://leetcode.com/problems/string-to-integer-atoi/', ARRAY['Amazon','Microsoft'], 'Strings'),
('Count and Say', 'Strings', 'Medium', 'https://leetcode.com/problems/count-and-say/', ARRAY['Facebook'], 'Strings'),
('Implement strStr()', 'Strings', 'Easy', 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/', ARRAY['Facebook','Microsoft'], 'Strings'),
('Longest Common Prefix', 'Strings', 'Easy', 'https://leetcode.com/problems/longest-common-prefix/', ARRAY['Amazon','Google'], 'Strings'),
('Reverse String', 'Strings', 'Easy', 'https://leetcode.com/problems/reverse-string/', ARRAY['Amazon'], 'Two Pointers'),
('Reverse Words in a String', 'Strings', 'Medium', 'https://leetcode.com/problems/reverse-words-in-a-string/', ARRAY['Amazon','Microsoft'], 'Strings'),
('Roman to Integer', 'Strings', 'Easy', 'https://leetcode.com/problems/roman-to-integer/', ARRAY['Amazon','Facebook'], 'Strings'),
('Integer to Roman', 'Strings', 'Medium', 'https://leetcode.com/problems/integer-to-roman/', ARRAY['Amazon'], 'Strings'),
('Zigzag Conversion', 'Strings', 'Medium', 'https://leetcode.com/problems/zigzag-conversion/', ARRAY['Amazon'], 'Strings'),
('Multiply Strings', 'Strings', 'Medium', 'https://leetcode.com/problems/multiply-strings/', ARRAY['Facebook','Google'], 'Strings'),
('Add Binary', 'Strings', 'Easy', 'https://leetcode.com/problems/add-binary/', ARRAY['Facebook','Amazon'], 'Strings'),
('Find All Anagrams in a String', 'Strings', 'Medium', 'https://leetcode.com/problems/find-all-anagrams-in-a-string/', ARRAY['Facebook'], 'Sliding Window'),
('Permutation in String', 'Strings', 'Medium', 'https://leetcode.com/problems/permutation-in-string/', ARRAY['Microsoft'], 'Sliding Window'),
('Ransom Note', 'Strings', 'Easy', 'https://leetcode.com/problems/ransom-note/', ARRAY['Amazon','Google'], 'Hash Map'),
('Isomorphic Strings', 'Strings', 'Easy', 'https://leetcode.com/problems/isomorphic-strings/', ARRAY['LinkedIn'], 'Hash Map'),
('Word Pattern', 'Strings', 'Easy', 'https://leetcode.com/problems/word-pattern/', ARRAY['Dropbox'], 'Hash Map'),
('Regular Expression Matching', 'Strings', 'Hard', 'https://leetcode.com/problems/regular-expression-matching/', ARRAY['Google','Facebook','Microsoft'], 'Dynamic Programming'),
('Wildcard Matching', 'Strings', 'Hard', 'https://leetcode.com/problems/wildcard-matching/', ARRAY['Google','Facebook'], 'Dynamic Programming'),
('Decode Ways', 'Strings', 'Medium', 'https://leetcode.com/problems/decode-ways/', ARRAY['Facebook','Amazon'], 'Dynamic Programming'),
('Letter Combinations of a Phone Number', 'Strings', 'Medium', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', ARRAY['Amazon','Facebook','Google'], 'Backtracking'),
('Generate Parentheses', 'Strings', 'Medium', 'https://leetcode.com/problems/generate-parentheses/', ARRAY['Amazon','Google'], 'Backtracking'),
('Valid Parentheses', 'Strings', 'Easy', 'https://leetcode.com/problems/valid-parentheses/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Stack'),
('Longest Valid Parentheses', 'Strings', 'Hard', 'https://leetcode.com/problems/longest-valid-parentheses/', ARRAY['Amazon','Google'], 'Stack'),
('Minimum Remove to Make Valid Parentheses', 'Strings', 'Medium', 'https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/', ARRAY['Facebook'], 'Stack'),
('Basic Calculator', 'Strings', 'Hard', 'https://leetcode.com/problems/basic-calculator/', ARRAY['Google'], 'Stack'),
('Basic Calculator II', 'Strings', 'Medium', 'https://leetcode.com/problems/basic-calculator-ii/', ARRAY['Amazon','Facebook'], 'Stack'),
('Text Justification', 'Strings', 'Hard', 'https://leetcode.com/problems/text-justification/', ARRAY['Airbnb','Google'], 'Strings'),
('Shortest Palindrome', 'Strings', 'Hard', 'https://leetcode.com/problems/shortest-palindrome/', ARRAY['Google'], 'KMP'),
('Repeated Substring Pattern', 'Strings', 'Easy', 'https://leetcode.com/problems/repeated-substring-pattern/', ARRAY['Amazon'], 'Strings'),
('Detect Capital', 'Strings', 'Easy', 'https://leetcode.com/problems/detect-capital/', ARRAY['Google'], 'Strings'),
('Anagram Search in String', 'Strings', 'Medium', 'https://www.geeksforgeeks.org/problems/anagram-search-in-string/1', ARRAY['Amazon'], 'Sliding Window'),
('Longest Common Substring', 'Strings', 'Medium', 'https://www.geeksforgeeks.org/problems/longest-common-substring1452/1', ARRAY['Amazon','Microsoft'], 'Dynamic Programming'),
('Roman Number to Integer', 'Strings', 'Easy', 'https://www.geeksforgeeks.org/problems/roman-number-to-integer3201/1', ARRAY['TCS'], 'Strings'),
('Parenthesis Checker', 'Strings', 'Easy', 'https://www.geeksforgeeks.org/problems/parenthesis-checker2744/1', ARRAY['Amazon'], 'Stack'),
('KMP Algorithm', 'Strings', 'Medium', 'https://www.geeksforgeeks.org/problems/search-pattern0205/1', ARRAY['Google','Amazon'], 'Strings'),
('Rabin Karp Algorithm', 'Strings', 'Medium', 'https://www.geeksforgeeks.org/problems/implement-rabin-karp/1', ARRAY['Google'], 'Strings'),
('Palindrome String', 'Strings', 'Easy', 'https://www.geeksforgeeks.org/problems/palindrome-string0817/1', ARRAY['TCS','Wipro'], 'Strings'),
('Reverse Words in String GFG', 'Strings', 'Easy', 'https://www.geeksforgeeks.org/problems/reverse-words-in-a-given-string5459/1', ARRAY['Amazon'], 'Strings'),
('Count Palindromic Substrings', 'Strings', 'Medium', 'https://www.geeksforgeeks.org/problems/count-palindrome-sub-strings-of-a-string0652/1', ARRAY['Google'], 'Dynamic Programming'),
('Minimum Characters to Add for Palindrome', 'Strings', 'Hard', 'https://www.geeksforgeeks.org/problems/minimum-characters-to-be-added-at-front-to-make-string-palindrome/1', ARRAY['Google'], 'Strings'),
('Longest Palindrome in a String', 'Strings', 'Medium', 'https://www.geeksforgeeks.org/problems/longest-palindrome-in-a-string3411/1', ARRAY['Amazon','Microsoft'], 'Dynamic Programming'),

-- ============================================================
-- LINKED LIST (35 problems)
-- ============================================================
('Reverse Linked List', 'Linked List', 'Easy', 'https://leetcode.com/problems/reverse-linked-list/', ARRAY['Amazon','Facebook','Microsoft'], 'Linked List'),
('Merge Two Sorted Lists', 'Linked List', 'Easy', 'https://leetcode.com/problems/merge-two-sorted-lists/', ARRAY['Amazon','Facebook','Microsoft'], 'Linked List'),
('Linked List Cycle', 'Linked List', 'Easy', 'https://leetcode.com/problems/linked-list-cycle/', ARRAY['Amazon','Microsoft'], 'Two Pointers'),
('Linked List Cycle II', 'Linked List', 'Medium', 'https://leetcode.com/problems/linked-list-cycle-ii/', ARRAY['Amazon'], 'Two Pointers'),
('Remove Nth Node From End of List', 'Linked List', 'Medium', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', ARRAY['Amazon','Microsoft'], 'Two Pointers'),
('Merge K Sorted Lists', 'Linked List', 'Hard', 'https://leetcode.com/problems/merge-k-sorted-lists/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Heap'),
('Reverse Nodes in K-Group', 'Linked List', 'Hard', 'https://leetcode.com/problems/reverse-nodes-in-k-group/', ARRAY['Amazon','Microsoft'], 'Linked List'),
('Copy List with Random Pointer', 'Linked List', 'Medium', 'https://leetcode.com/problems/copy-list-with-random-pointer/', ARRAY['Amazon','Microsoft'], 'Hash Map'),
('Add Two Numbers', 'Linked List', 'Medium', 'https://leetcode.com/problems/add-two-numbers/', ARRAY['Amazon','Facebook','Microsoft'], 'Linked List'),
('Intersection of Two Linked Lists', 'Linked List', 'Easy', 'https://leetcode.com/problems/intersection-of-two-linked-lists/', ARRAY['Amazon','Microsoft'], 'Two Pointers'),
('Palindrome Linked List', 'Linked List', 'Easy', 'https://leetcode.com/problems/palindrome-linked-list/', ARRAY['Amazon','Facebook'], 'Two Pointers'),
('Remove Duplicates from Sorted List', 'Linked List', 'Easy', 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/', ARRAY['Microsoft'], 'Linked List'),
('Remove Duplicates from Sorted List II', 'Linked List', 'Medium', 'https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/', ARRAY['Microsoft'], 'Linked List'),
('Rotate List', 'Linked List', 'Medium', 'https://leetcode.com/problems/rotate-list/', ARRAY['Amazon'], 'Linked List'),
('Partition List', 'Linked List', 'Medium', 'https://leetcode.com/problems/partition-list/', ARRAY['Amazon'], 'Linked List'),
('Sort List', 'Linked List', 'Medium', 'https://leetcode.com/problems/sort-list/', ARRAY['Amazon','Facebook'], 'Merge Sort'),
('Reorder List', 'Linked List', 'Medium', 'https://leetcode.com/problems/reorder-list/', ARRAY['Amazon'], 'Two Pointers'),
('LRU Cache', 'Linked List', 'Medium', 'https://leetcode.com/problems/lru-cache/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Hash Map'),
('Flatten a Multilevel Doubly Linked List', 'Linked List', 'Medium', 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/', ARRAY['Microsoft'], 'Linked List'),
('Odd Even Linked List', 'Linked List', 'Medium', 'https://leetcode.com/problems/odd-even-linked-list/', ARRAY['Microsoft'], 'Linked List'),
('Swap Nodes in Pairs', 'Linked List', 'Medium', 'https://leetcode.com/problems/swap-nodes-in-pairs/', ARRAY['Amazon'], 'Linked List'),
('Middle of the Linked List', 'Linked List', 'Easy', 'https://leetcode.com/problems/middle-of-the-linked-list/', ARRAY['Amazon'], 'Two Pointers'),
('Delete Node in a Linked List', 'Linked List', 'Medium', 'https://leetcode.com/problems/delete-node-in-a-linked-list/', ARRAY['Amazon'], 'Linked List'),
('Reverse Linked List II', 'Linked List', 'Medium', 'https://leetcode.com/problems/reverse-linked-list-ii/', ARRAY['Facebook'], 'Linked List'),
('Design Linked List', 'Linked List', 'Medium', 'https://leetcode.com/problems/design-linked-list/', ARRAY['Amazon'], 'Linked List'),
('Reverse a Linked List GFG', 'Linked List', 'Easy', 'https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1', ARRAY['Amazon','Microsoft'], 'Linked List'),
('Detect Loop in Linked List', 'Linked List', 'Easy', 'https://www.geeksforgeeks.org/problems/detect-loop-in-linked-list/1', ARRAY['Amazon'], 'Two Pointers'),
('Remove Loop in Linked List', 'Linked List', 'Medium', 'https://www.geeksforgeeks.org/problems/remove-loop-in-linked-list/1', ARRAY['Amazon'], 'Two Pointers'),
('Nth Node from End of List GFG', 'Linked List', 'Easy', 'https://www.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1', ARRAY['Amazon'], 'Two Pointers'),
('Merge Two Sorted Linked Lists GFG', 'Linked List', 'Easy', 'https://www.geeksforgeeks.org/problems/merge-two-sorted-linked-lists/1', ARRAY['Amazon'], 'Linked List'),
('Flattening a Linked List GFG', 'Linked List', 'Medium', 'https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1', ARRAY['Flipkart'], 'Linked List'),
('Clone a Linked List with Next and Random Pointer GFG', 'Linked List', 'Hard', 'https://www.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1', ARRAY['Amazon'], 'Hash Map'),
('Add Two Numbers Represented as Linked Lists', 'Linked List', 'Medium', 'https://www.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1', ARRAY['Amazon','Flipkart'], 'Linked List'),
('Segregate Even and Odd Nodes', 'Linked List', 'Easy', 'https://www.geeksforgeeks.org/problems/segregate-even-and-odd-nodes-in-a-linked-list5035/1', ARRAY['Microsoft'], 'Linked List'),
('Delete Without Head Pointer', 'Linked List', 'Easy', 'https://www.geeksforgeeks.org/problems/delete-without-head-pointer/1', ARRAY['Amazon'], 'Linked List'),

-- ============================================================
-- TREES (55 problems)
-- ============================================================
('Maximum Depth of Binary Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', ARRAY['Amazon','Facebook','LinkedIn'], 'DFS'),
('Same Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/same-tree/', ARRAY['Amazon'], 'DFS'),
('Invert Binary Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/invert-binary-tree/', ARRAY['Google','Amazon','Facebook'], 'DFS'),
('Binary Tree Maximum Path Sum', 'Trees', 'Hard', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', ARRAY['Facebook','Amazon','Google'], 'DFS'),
('Binary Tree Level Order Traversal', 'Trees', 'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'BFS'),
('Serialize and Deserialize Binary Tree', 'Trees', 'Hard', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', ARRAY['Facebook','Google','Amazon'], 'DFS'),
('Subtree of Another Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/subtree-of-another-tree/', ARRAY['Amazon','Facebook'], 'DFS'),
('Construct Binary Tree from Preorder and Inorder Traversal', 'Trees', 'Medium', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', ARRAY['Amazon','Microsoft'], 'DFS'),
('Validate Binary Search Tree', 'Trees', 'Medium', 'https://leetcode.com/problems/validate-binary-search-tree/', ARRAY['Amazon','Facebook','Microsoft'], 'DFS'),
('Kth Smallest Element in a BST', 'Trees', 'Medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', ARRAY['Amazon','Google'], 'DFS'),
('Lowest Common Ancestor of a Binary Search Tree', 'Trees', 'Medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', ARRAY['Amazon','Facebook','Microsoft'], 'DFS'),
('Lowest Common Ancestor of a Binary Tree', 'Trees', 'Medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', ARRAY['Amazon','Facebook','Microsoft'], 'DFS'),
('Implement Trie (Prefix Tree)', 'Trees', 'Medium', 'https://leetcode.com/problems/implement-trie-prefix-tree/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Trie'),
('Add and Search Word', 'Trees', 'Medium', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', ARRAY['Facebook'], 'Trie'),
('Word Search II', 'Trees', 'Hard', 'https://leetcode.com/problems/word-search-ii/', ARRAY['Amazon','Microsoft'], 'Trie'),
('Symmetric Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/symmetric-tree/', ARRAY['Amazon','Microsoft'], 'DFS'),
('Path Sum', 'Trees', 'Easy', 'https://leetcode.com/problems/path-sum/', ARRAY['Amazon','Microsoft'], 'DFS'),
('Path Sum II', 'Trees', 'Medium', 'https://leetcode.com/problems/path-sum-ii/', ARRAY['Amazon'], 'Backtracking'),
('Flatten Binary Tree to Linked List', 'Trees', 'Medium', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', ARRAY['Microsoft'], 'DFS'),
('Populating Next Right Pointers in Each Node', 'Trees', 'Medium', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', ARRAY['Microsoft'], 'BFS'),
('Binary Tree Right Side View', 'Trees', 'Medium', 'https://leetcode.com/problems/binary-tree-right-side-view/', ARRAY['Facebook','Amazon'], 'BFS'),
('Count Complete Tree Nodes', 'Trees', 'Easy', 'https://leetcode.com/problems/count-complete-tree-nodes/', ARRAY['Google'], 'Binary Search'),
('Binary Tree Zigzag Level Order Traversal', 'Trees', 'Medium', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/', ARRAY['Amazon','Microsoft'], 'BFS'),
('Sum Root to Leaf Numbers', 'Trees', 'Medium', 'https://leetcode.com/problems/sum-root-to-leaf-numbers/', ARRAY['Google'], 'DFS'),
('Recover Binary Search Tree', 'Trees', 'Medium', 'https://leetcode.com/problems/recover-binary-search-tree/', ARRAY['Microsoft'], 'DFS'),
('Convert Sorted Array to Binary Search Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/', ARRAY['Amazon'], 'DFS'),
('Balanced Binary Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/balanced-binary-tree/', ARRAY['Amazon','Facebook'], 'DFS'),
('Minimum Depth of Binary Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/minimum-depth-of-binary-tree/', ARRAY['Amazon'], 'BFS'),
('Average of Levels in Binary Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/average-of-levels-in-binary-tree/', ARRAY['Facebook'], 'BFS'),
('Find Largest Value in Each Tree Row', 'Trees', 'Medium', 'https://leetcode.com/problems/find-largest-value-in-each-tree-row/', ARRAY['LinkedIn'], 'BFS'),
('Delete Node in a BST', 'Trees', 'Medium', 'https://leetcode.com/problems/delete-node-in-a-bst/', ARRAY['Amazon'], 'BST'),
('Insert into a Binary Search Tree', 'Trees', 'Medium', 'https://leetcode.com/problems/insert-into-a-binary-search-tree/', ARRAY['Amazon'], 'BST'),
('Search in a Binary Search Tree', 'Trees', 'Easy', 'https://leetcode.com/problems/search-in-a-binary-search-tree/', ARRAY['Amazon'], 'BST'),
('Range Sum of BST', 'Trees', 'Easy', 'https://leetcode.com/problems/range-sum-of-bst/', ARRAY['Amazon'], 'DFS'),
('All Nodes Distance K in Binary Tree', 'Trees', 'Medium', 'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/', ARRAY['Google'], 'BFS'),
('Binary Tree Inorder Traversal GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/inorder-traversal/1', ARRAY['Amazon'], 'DFS'),
('Height of Binary Tree GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/height-of-binary-tree/1', ARRAY['Amazon'], 'DFS'),
('Mirror Tree GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/mirror-tree/1', ARRAY['Amazon'], 'DFS'),
('Diameter of Binary Tree GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1', ARRAY['Amazon'], 'DFS'),
('Level Order Traversal GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/level-order-traversal/1', ARRAY['Amazon'], 'BFS'),
('Check for BST GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/check-for-bst/1', ARRAY['Amazon'], 'DFS'),
('Vertical Order Traversal GFG', 'Trees', 'Medium', 'https://www.geeksforgeeks.org/problems/print-a-binary-tree-in-vertical-order/1', ARRAY['Amazon','Flipkart'], 'BFS'),
('Top View of Binary Tree GFG', 'Trees', 'Medium', 'https://www.geeksforgeeks.org/problems/top-view-of-binary-tree/1', ARRAY['Flipkart','Amazon'], 'BFS'),
('Bottom View of Binary Tree GFG', 'Trees', 'Medium', 'https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1', ARRAY['Flipkart'], 'BFS'),
('Left View of Binary Tree GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/left-view-of-binary-tree/1', ARRAY['Amazon','Flipkart'], 'BFS'),
('Right View of Binary Tree GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/right-view-of-binary-tree/1', ARRAY['Amazon'], 'BFS'),
('Boundary Traversal of Binary Tree GFG', 'Trees', 'Medium', 'https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1', ARRAY['Amazon'], 'DFS'),
('Morris Traversal GFG', 'Trees', 'Hard', 'https://www.geeksforgeeks.org/problems/inorder-traversal-iterative/1', ARRAY['Google'], 'DFS'),
('Serialize and Deserialize GFG', 'Trees', 'Medium', 'https://www.geeksforgeeks.org/problems/serialize-and-deserialize-a-binary-tree/1', ARRAY['Amazon'], 'DFS'),
('Lowest Common Ancestor GFG', 'Trees', 'Medium', 'https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1', ARRAY['Amazon','Microsoft'], 'DFS'),
('Burning Tree GFG', 'Trees', 'Hard', 'https://www.geeksforgeeks.org/problems/burning-tree/1', ARRAY['Amazon','Flipkart'], 'BFS'),
('Flatten BST to Sorted List GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/flatten-bst-to-sorted-list--170645/1', ARRAY['Amazon'], 'DFS'),
('K Distance from Root GFG', 'Trees', 'Easy', 'https://www.geeksforgeeks.org/problems/k-distance-from-root/1', ARRAY['Amazon'], 'DFS'),
('Maximum Path Sum between Two Leaves GFG', 'Trees', 'Hard', 'https://www.geeksforgeeks.org/problems/maximum-path-sum-from-any-node/1', ARRAY['Amazon'], 'DFS'),
('Duplicate Subtree in Binary Tree GFG', 'Trees', 'Medium', 'https://www.geeksforgeeks.org/problems/duplicate-subtree-in-binary-tree/1', ARRAY['Amazon'], 'Hashing'),

-- ============================================================
-- DYNAMIC PROGRAMMING (60 problems)
-- ============================================================
('Climbing Stairs', 'Dynamic Programming', 'Easy', 'https://leetcode.com/problems/climbing-stairs/', ARRAY['Amazon','Apple','Google'], 'Dynamic Programming'),
('House Robber', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/house-robber/', ARRAY['Amazon'], 'Dynamic Programming'),
('House Robber II', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/house-robber-ii/', ARRAY['Amazon'], 'Dynamic Programming'),
('Longest Palindromic Subsequence', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/longest-palindromic-subsequence/', ARRAY['Amazon'], 'Dynamic Programming'),
('Longest Increasing Subsequence', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/longest-increasing-subsequence/', ARRAY['Amazon','Microsoft','Google'], 'Dynamic Programming'),
('Coin Change', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/coin-change/', ARRAY['Amazon','Google','Microsoft'], 'Dynamic Programming'),
('Coin Change II', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/coin-change-ii/', ARRAY['Amazon'], 'Dynamic Programming'),
('Longest Common Subsequence', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/longest-common-subsequence/', ARRAY['Amazon','Google'], 'Dynamic Programming'),
('Edit Distance', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/edit-distance/', ARRAY['Amazon','Google','Microsoft'], 'Dynamic Programming'),
('Unique Paths', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/unique-paths/', ARRAY['Amazon','Microsoft'], 'Dynamic Programming'),
('Unique Paths II', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/unique-paths-ii/', ARRAY['Amazon','Microsoft'], 'Dynamic Programming'),
('Minimum Path Sum', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/minimum-path-sum/', ARRAY['Amazon','Google'], 'Dynamic Programming'),
('Word Break', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/word-break/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'Dynamic Programming'),
('Word Break II', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/word-break-ii/', ARRAY['Amazon','Google'], 'Backtracking'),
('Partition Equal Subset Sum', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/partition-equal-subset-sum/', ARRAY['Amazon','Facebook'], 'Dynamic Programming'),
('Target Sum', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/target-sum/', ARRAY['Amazon'], 'Dynamic Programming'),
('Interleaving String', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/interleaving-string/', ARRAY['Google'], 'Dynamic Programming'),
('Distinct Subsequences', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/distinct-subsequences/', ARRAY['Google'], 'Dynamic Programming'),
('Burst Balloons', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/burst-balloons/', ARRAY['Google'], 'Dynamic Programming'),
('Regular Expression Matching DP', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/regular-expression-matching/', ARRAY['Google','Facebook','Microsoft'], 'Dynamic Programming'),
('Maximum Rectangle', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/maximal-rectangle/', ARRAY['Amazon'], 'Stack'),
('Largest Rectangle in Histogram', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/', ARRAY['Amazon','Facebook'], 'Stack'),
('Maximal Square', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/maximal-square/', ARRAY['Facebook','Amazon'], 'Dynamic Programming'),
('Triangle', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/triangle/', ARRAY['Amazon'], 'Dynamic Programming'),
('Dungeon Game', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/dungeon-game/', ARRAY['Google'], 'Dynamic Programming'),
('Palindrome Partitioning II', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/palindrome-partitioning-ii/', ARRAY['Amazon'], 'Dynamic Programming'),
('Matrix Chain Multiplication GFG', 'Dynamic Programming', 'Hard', 'https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1', ARRAY['Amazon','Google'], 'Dynamic Programming'),
('0-1 Knapsack GFG', 'Dynamic Programming', 'Medium', 'https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1', ARRAY['Amazon','Microsoft'], 'Dynamic Programming'),
('Fractional Knapsack GFG', 'Dynamic Programming', 'Medium', 'https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1', ARRAY['Amazon'], 'Greedy'),
('Egg Dropping Puzzle GFG', 'Dynamic Programming', 'Hard', 'https://www.geeksforgeeks.org/problems/egg-dropping-puzzle-1587115620/1', ARRAY['Amazon','Google'], 'Dynamic Programming'),
('Optimal Strategy for a Game GFG', 'Dynamic Programming', 'Medium', 'https://www.geeksforgeeks.org/problems/optimal-strategy-for-a-game-1587115620/1', ARRAY['Amazon'], 'Dynamic Programming'),
('Staircase Problem GFG', 'Dynamic Programming', 'Easy', 'https://www.geeksforgeeks.org/problems/count-ways-to-reach-the-nth-stair-1587115621/1', ARRAY['Amazon'], 'Dynamic Programming'),
('Minimum Number of Jumps GFG', 'Dynamic Programming', 'Medium', 'https://www.geeksforgeeks.org/problems/minimum-number-of-jumps-1587115620/1', ARRAY['Amazon'], 'Dynamic Programming'),
('Weighted Job Scheduling GFG', 'Dynamic Programming', 'Hard', 'https://www.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1', ARRAY['Amazon'], 'Dynamic Programming'),
('Longest Bitonic Subsequence GFG', 'Dynamic Programming', 'Medium', 'https://www.geeksforgeeks.org/problems/longest-bitonic-subsequence0824/1', ARRAY['Amazon'], 'Dynamic Programming'),
('Maximum Sum Increasing Subsequence GFG', 'Dynamic Programming', 'Medium', 'https://www.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4containers/1', ARRAY['Amazon'], 'Dynamic Programming'),
('Count Subsequences of Type a^i b^j c^k GFG', 'Dynamic Programming', 'Hard', 'https://www.geeksforgeeks.org/problems/count-subsequences-of-type-ai-bj-ck4628/1', ARRAY['Google'], 'Dynamic Programming'),
('Boolean Parenthesization GFG', 'Dynamic Programming', 'Hard', 'https://www.geeksforgeeks.org/problems/boolean-parenthesization5610/1', ARRAY['Amazon'], 'Dynamic Programming'),
('Mobile Numeric Keypad GFG', 'Dynamic Programming', 'Medium', 'https://www.geeksforgeeks.org/problems/mobile-numeric-keypad5456/1', ARRAY['Samsung'], 'Dynamic Programming'),
('Maximum Profit in Job Scheduling', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/maximum-profit-in-job-scheduling/', ARRAY['Google'], 'Dynamic Programming'),
('Minimum Cost to Cut a Stick', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/', ARRAY['Amazon'], 'Dynamic Programming'),
('Strange Printer', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/strange-printer/', ARRAY['Google'], 'Dynamic Programming'),
('Paint Houses', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/paint-house/', ARRAY['Facebook'], 'Dynamic Programming'),
('Decode Ways', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/decode-ways/', ARRAY['Facebook','Amazon'], 'Dynamic Programming'),
('Number of Dice Rolls With Target Sum', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/', ARRAY['Google'], 'Dynamic Programming'),
('Combination Sum IV', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/combination-sum-iv/', ARRAY['Google','Facebook'], 'Dynamic Programming'),
('Count Square Submatrices with All Ones', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/count-square-submatrices-with-all-ones/', ARRAY['Google'], 'Dynamic Programming'),
('Minimum Falling Path Sum', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/minimum-falling-path-sum/', ARRAY['Google'], 'Dynamic Programming'),
('Longest Turbulent Subarray', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/longest-turbulent-subarray/', ARRAY['Google'], 'Dynamic Programming'),
('Maximum Length of Repeated Subarray', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/maximum-length-of-repeated-subarray/', ARRAY['Amazon'], 'Dynamic Programming'),
('Uncrossed Lines', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/uncrossed-lines/', ARRAY['Amazon'], 'Dynamic Programming'),
('Cherry Pickup', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/cherry-pickup/', ARRAY['Google'], 'Dynamic Programming'),
('Student Attendance Record II', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/student-attendance-record-ii/', ARRAY['Google'], 'Dynamic Programming'),
('Predict the Winner', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/predict-the-winner/', ARRAY['Google'], 'Dynamic Programming'),
('Stone Game', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/stone-game/', ARRAY['Amazon'], 'Dynamic Programming'),
('Minimum Score Triangulation of Polygon', 'Dynamic Programming', 'Medium', 'https://leetcode.com/problems/minimum-score-triangulation-of-polygon/', ARRAY['Google'], 'Dynamic Programming'),
('Frog Jump', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/frog-jump/', ARRAY['Amazon','Google'], 'Dynamic Programming'),
('Race Car', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/race-car/', ARRAY['Google'], 'Dynamic Programming'),
('Freedom Trail', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/freedom-trail/', ARRAY['Google'], 'Dynamic Programming'),
('Tallest Billboard', 'Dynamic Programming', 'Hard', 'https://leetcode.com/problems/tallest-billboard/', ARRAY['Google'], 'Dynamic Programming'),

-- ============================================================
-- GRAPHS (55 problems)
-- ============================================================
('Number of Islands', 'Graphs', 'Medium', 'https://leetcode.com/problems/number-of-islands/', ARRAY['Amazon','Facebook','Google','Microsoft'], 'DFS'),
('Clone Graph', 'Graphs', 'Medium', 'https://leetcode.com/problems/clone-graph/', ARRAY['Amazon','Facebook'], 'BFS'),
('Pacific Atlantic Water Flow', 'Graphs', 'Medium', 'https://leetcode.com/problems/pacific-atlantic-water-flow/', ARRAY['Google'], 'DFS'),
('Course Schedule', 'Graphs', 'Medium', 'https://leetcode.com/problems/course-schedule/', ARRAY['Amazon','Facebook','Google'], 'Topological Sort'),
('Course Schedule II', 'Graphs', 'Medium', 'https://leetcode.com/problems/course-schedule-ii/', ARRAY['Amazon','Facebook','Google'], 'Topological Sort'),
('Word Ladder', 'Graphs', 'Hard', 'https://leetcode.com/problems/word-ladder/', ARRAY['Amazon','Facebook','Google'], 'BFS'),
('Graph Valid Tree', 'Graphs', 'Medium', 'https://leetcode.com/problems/graph-valid-tree/', ARRAY['Google','LinkedIn'], 'Union Find'),
('Number of Connected Components in an Undirected Graph', 'Graphs', 'Medium', 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', ARRAY['Google','LinkedIn'], 'Union Find'),
('Alien Dictionary', 'Graphs', 'Hard', 'https://leetcode.com/problems/alien-dictionary/', ARRAY['Airbnb','Facebook','Google'], 'Topological Sort'),
('Cheapest Flights Within K Stops', 'Graphs', 'Medium', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', ARRAY['Amazon'], 'Dijkstra'),
('Network Delay Time', 'Graphs', 'Medium', 'https://leetcode.com/problems/network-delay-time/', ARRAY['Amazon'], 'Dijkstra'),
('Reconstruct Itinerary', 'Graphs', 'Hard', 'https://leetcode.com/problems/reconstruct-itinerary/', ARRAY['Google'], 'DFS'),
('Surrounded Regions', 'Graphs', 'Medium', 'https://leetcode.com/problems/surrounded-regions/', ARRAY['Amazon'], 'DFS'),
('Walls and Gates', 'Graphs', 'Medium', 'https://leetcode.com/problems/walls-and-gates/', ARRAY['Facebook'], 'BFS'),
('Rotting Oranges', 'Graphs', 'Medium', 'https://leetcode.com/problems/rotting-oranges/', ARRAY['Amazon'], 'BFS'),
('01 Matrix', 'Graphs', 'Medium', 'https://leetcode.com/problems/01-matrix/', ARRAY['Facebook'], 'BFS'),
('Shortest Path in Binary Matrix', 'Graphs', 'Medium', 'https://leetcode.com/problems/shortest-path-in-binary-matrix/', ARRAY['Google'], 'BFS'),
('Find the Town Judge', 'Graphs', 'Easy', 'https://leetcode.com/problems/find-the-town-judge/', ARRAY['Amazon'], 'Graphs'),
('Is Graph Bipartite', 'Graphs', 'Medium', 'https://leetcode.com/problems/is-graph-bipartite/', ARRAY['Google'], 'BFS'),
('Find Eventual Safe States', 'Graphs', 'Medium', 'https://leetcode.com/problems/find-eventual-safe-states/', ARRAY['Google'], 'DFS'),
('Redundant Connection', 'Graphs', 'Medium', 'https://leetcode.com/problems/redundant-connection/', ARRAY['Google'], 'Union Find'),
('Critical Connections in a Network', 'Graphs', 'Hard', 'https://leetcode.com/problems/critical-connections-in-a-network/', ARRAY['Amazon'], 'DFS'),
('Max Area of Island', 'Graphs', 'Medium', 'https://leetcode.com/problems/max-area-of-island/', ARRAY['Amazon','Facebook'], 'DFS'),
('Flood Fill', 'Graphs', 'Easy', 'https://leetcode.com/problems/flood-fill/', ARRAY['Facebook'], 'DFS'),
('Number of Provinces', 'Graphs', 'Medium', 'https://leetcode.com/problems/number-of-provinces/', ARRAY['Amazon'], 'Union Find'),
('Keys and Rooms', 'Graphs', 'Medium', 'https://leetcode.com/problems/keys-and-rooms/', ARRAY['Google'], 'DFS'),
('All Paths From Source to Target', 'Graphs', 'Medium', 'https://leetcode.com/problems/all-paths-from-source-to-target/', ARRAY['Google'], 'DFS'),
('Minimum Number of Vertices to Reach All Nodes', 'Graphs', 'Medium', 'https://leetcode.com/problems/minimum-number-of-vertices-to-reach-all-nodes/', ARRAY['Amazon'], 'Graphs'),
('Accounts Merge', 'Graphs', 'Medium', 'https://leetcode.com/problems/accounts-merge/', ARRAY['Facebook','Amazon'], 'Union Find'),
('Most Stones Removed with Same Row or Column', 'Graphs', 'Medium', 'https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/', ARRAY['Facebook'], 'Union Find'),
('Minimum Spanning Tree GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1', ARRAY['Amazon','Microsoft'], 'Prim'),
('Dijkstra Algorithm GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1', ARRAY['Amazon','Ola'], 'Dijkstra'),
('Bellman-Ford GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1', ARRAY['Amazon'], 'Bellman-Ford'),
('Floyd Warshall GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1', ARRAY['Amazon'], 'Floyd-Warshall'),
('Topological Sort GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/topological-sort/1', ARRAY['Amazon','Flipkart'], 'Topological Sort'),
('Strongly Connected Components GFG', 'Graphs', 'Hard', 'https://www.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1', ARRAY['Amazon'], 'DFS'),
('Articulation Point GFG', 'Graphs', 'Hard', 'https://www.geeksforgeeks.org/problems/articulation-point-1/1', ARRAY['Amazon'], 'DFS'),
('Bridge Edge in Graph GFG', 'Graphs', 'Hard', 'https://www.geeksforgeeks.org/problems/bridge-edge-in-graph/1', ARRAY['Amazon'], 'DFS'),
('Shortest Source to Destination Path GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/shortest-source-to-destination-path3544/1', ARRAY['Amazon'], 'BFS'),
('Find Whether Path Exists GFG', 'Graphs', 'Easy', 'https://www.geeksforgeeks.org/problems/find-whether-path-exist5238/1', ARRAY['Amazon'], 'DFS'),
('Snake and Ladder Problem GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/snake-and-ladder-problem4816/1', ARRAY['Amazon'], 'BFS'),
('Knight Walk GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/knight-walk4916/1', ARRAY['Amazon'], 'BFS'),
('Alien Dictionary GFG', 'Graphs', 'Hard', 'https://www.geeksforgeeks.org/problems/alien-dictionary/1', ARRAY['Amazon','Flipkart'], 'Topological Sort'),
('Bipartite Graph GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/bipartite-graph/1', ARRAY['Amazon'], 'BFS'),
('Detect Cycle in Undirected Graph GFG', 'Graphs', 'Easy', 'https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1', ARRAY['Amazon'], 'DFS'),
('Detect Cycle in Directed Graph GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1', ARRAY['Amazon'], 'DFS'),
('Word Search', 'Graphs', 'Medium', 'https://leetcode.com/problems/word-search/', ARRAY['Amazon','Microsoft'], 'DFS'),
('Number of Distinct Islands GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/number-of-distinct-islands/1', ARRAY['Amazon'], 'DFS'),
('Minimum Steps by Knight GFG', 'Graphs', 'Medium', 'https://www.geeksforgeeks.org/problems/steps-by-knight5927/1', ARRAY['Amazon'], 'BFS'),
('Mother Vertex GFG', 'Graphs', 'Easy', 'https://www.geeksforgeeks.org/problems/mother-vertex/1', ARRAY['Amazon'], 'DFS'),
('Number of Operations to Make Network Connected', 'Graphs', 'Medium', 'https://leetcode.com/problems/number-of-operations-to-make-network-connected/', ARRAY['Amazon'], 'Union Find'),
('Making a Large Island', 'Graphs', 'Hard', 'https://leetcode.com/problems/making-a-large-island/', ARRAY['Google'], 'Union Find'),
('Swim in Rising Water', 'Graphs', 'Hard', 'https://leetcode.com/problems/swim-in-rising-water/', ARRAY['Google'], 'Dijkstra'),
('Path With Maximum Probability', 'Graphs', 'Medium', 'https://leetcode.com/problems/path-with-maximum-probability/', ARRAY['Google'], 'Dijkstra'),
('Find the Safest Path in a Grid', 'Graphs', 'Medium', 'https://leetcode.com/problems/find-the-safest-path-in-a-grid/', ARRAY['Google'], 'BFS'),

-- ============================================================
-- BACKTRACKING (30 problems)
-- ============================================================
('Subsets', 'Backtracking', 'Medium', 'https://leetcode.com/problems/subsets/', ARRAY['Amazon','Facebook'], 'Backtracking'),
('Subsets II', 'Backtracking', 'Medium', 'https://leetcode.com/problems/subsets-ii/', ARRAY['Amazon'], 'Backtracking'),
('Permutations', 'Backtracking', 'Medium', 'https://leetcode.com/problems/permutations/', ARRAY['Amazon','Microsoft'], 'Backtracking'),
('Permutations II', 'Backtracking', 'Medium', 'https://leetcode.com/problems/permutations-ii/', ARRAY['Amazon'], 'Backtracking'),
('Combination Sum', 'Backtracking', 'Medium', 'https://leetcode.com/problems/combination-sum/', ARRAY['Amazon','Facebook'], 'Backtracking'),
('Combination Sum II', 'Backtracking', 'Medium', 'https://leetcode.com/problems/combination-sum-ii/', ARRAY['Amazon'], 'Backtracking'),
('Combination Sum III', 'Backtracking', 'Medium', 'https://leetcode.com/problems/combination-sum-iii/', ARRAY['Google'], 'Backtracking'),
('Palindrome Partitioning', 'Backtracking', 'Medium', 'https://leetcode.com/problems/palindrome-partitioning/', ARRAY['Amazon'], 'Backtracking'),
('N-Queens', 'Backtracking', 'Hard', 'https://leetcode.com/problems/n-queens/', ARRAY['Amazon','Google'], 'Backtracking'),
('N-Queens II', 'Backtracking', 'Hard', 'https://leetcode.com/problems/n-queens-ii/', ARRAY['Amazon'], 'Backtracking'),
('Sudoku Solver', 'Backtracking', 'Hard', 'https://leetcode.com/problems/sudoku-solver/', ARRAY['Amazon','Microsoft'], 'Backtracking'),
('Valid Sudoku', 'Backtracking', 'Medium', 'https://leetcode.com/problems/valid-sudoku/', ARRAY['Amazon'], 'Hash Map'),
('Rat in a Maze GFG', 'Backtracking', 'Medium', 'https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1', ARRAY['Amazon'], 'Backtracking'),
('N Queens GFG', 'Backtracking', 'Hard', 'https://www.geeksforgeeks.org/problems/n-queen-problem0315/1', ARRAY['Amazon'], 'Backtracking'),
('Sudoku Solver GFG', 'Backtracking', 'Hard', 'https://www.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1', ARRAY['Amazon'], 'Backtracking'),
('Permutations of a String GFG', 'Backtracking', 'Medium', 'https://www.geeksforgeeks.org/problems/permutations-of-a-given-string2229/1', ARRAY['Amazon'], 'Backtracking'),
('Power Set GFG', 'Backtracking', 'Easy', 'https://www.geeksforgeeks.org/problems/power-set4302/1', ARRAY['Amazon'], 'Backtracking'),
('Word Break GFG', 'Backtracking', 'Medium', 'https://www.geeksforgeeks.org/problems/word-break1352/1', ARRAY['Amazon','Google'], 'Dynamic Programming'),
('M Coloring Problem GFG', 'Backtracking', 'Medium', 'https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1', ARRAY['Amazon'], 'Backtracking'),
('Hamiltonian Path GFG', 'Backtracking', 'Hard', 'https://www.geeksforgeeks.org/problems/hamiltonian-path2522/1', ARRAY['Amazon'], 'Backtracking'),
('Tug of War GFG', 'Backtracking', 'Medium', 'https://www.geeksforgeeks.org/problems/tug-of-war/1', ARRAY['Amazon'], 'Backtracking'),
('Combinations', 'Backtracking', 'Medium', 'https://leetcode.com/problems/combinations/', ARRAY['Google'], 'Backtracking'),
('Restore IP Addresses', 'Backtracking', 'Medium', 'https://leetcode.com/problems/restore-ip-addresses/', ARRAY['Amazon'], 'Backtracking'),
('Letter Case Permutation', 'Backtracking', 'Medium', 'https://leetcode.com/problems/letter-case-permutation/', ARRAY['Facebook'], 'Backtracking'),
('Beautiful Arrangement', 'Backtracking', 'Medium', 'https://leetcode.com/problems/beautiful-arrangement/', ARRAY['Google'], 'Backtracking'),
('Remove Invalid Parentheses', 'Backtracking', 'Hard', 'https://leetcode.com/problems/remove-invalid-parentheses/', ARRAY['Facebook'], 'Backtracking'),
('Expression Add Operators', 'Backtracking', 'Hard', 'https://leetcode.com/problems/expression-add-operators/', ARRAY['Facebook','Amazon'], 'Backtracking'),
('24 Game', 'Backtracking', 'Hard', 'https://leetcode.com/problems/24-game/', ARRAY['Google'], 'Backtracking'),
('Zuma Game', 'Backtracking', 'Hard', 'https://leetcode.com/problems/zuma-game/', ARRAY['Google'], 'Dynamic Programming'),
('Generalized Abbreviation', 'Backtracking', 'Medium', 'https://leetcode.com/problems/generalized-abbreviation/', ARRAY['Palantir'], 'Backtracking'),

-- ============================================================
-- STACK & QUEUE (25 problems)
-- ============================================================
('Min Stack', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/min-stack/', ARRAY['Amazon','Google','Microsoft'], 'Stack'),
('Evaluate Reverse Polish Notation', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', ARRAY['Amazon','LinkedIn'], 'Stack'),
('Daily Temperatures', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/daily-temperatures/', ARRAY['Amazon'], 'Stack'),
('Car Fleet', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/car-fleet/', ARRAY['Google'], 'Stack'),
('Largest Rectangle in Histogram LC', 'Stack & Queue', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/', ARRAY['Amazon','Facebook'], 'Stack'),
('Next Greater Element I', 'Stack & Queue', 'Easy', 'https://leetcode.com/problems/next-greater-element-i/', ARRAY['Amazon'], 'Stack'),
('Next Greater Element II', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/next-greater-element-ii/', ARRAY['Amazon'], 'Stack'),
('Online Stock Span', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/online-stock-span/', ARRAY['Amazon'], 'Stack'),
('Implement Queue using Stacks', 'Stack & Queue', 'Easy', 'https://leetcode.com/problems/implement-queue-using-stacks/', ARRAY['Amazon','Microsoft'], 'Stack'),
('Implement Stack using Queues', 'Stack & Queue', 'Easy', 'https://leetcode.com/problems/implement-stack-using-queues/', ARRAY['Amazon'], 'Queue'),
('Design Circular Queue', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/design-circular-queue/', ARRAY['Amazon'], 'Queue'),
('Sliding Window Maximum LC', 'Stack & Queue', 'Hard', 'https://leetcode.com/problems/sliding-window-maximum/', ARRAY['Amazon','Google'], 'Deque'),
('Maximum Frequency Stack', 'Stack & Queue', 'Hard', 'https://leetcode.com/problems/maximum-frequency-stack/', ARRAY['Amazon'], 'Stack'),
('Asteroid Collision', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/asteroid-collision/', ARRAY['Amazon'], 'Stack'),
('Score of Parentheses', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/score-of-parentheses/', ARRAY['Google'], 'Stack'),
('Next Greater Element III', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/next-greater-element-iii/', ARRAY['Amazon'], 'Stack'),
('132 Pattern', 'Stack & Queue', 'Medium', 'https://leetcode.com/problems/132-pattern/', ARRAY['Google'], 'Stack'),
('Implement two stacks in an array GFG', 'Stack & Queue', 'Easy', 'https://www.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1', ARRAY['Amazon'], 'Stack'),
('Get Minimum Element from Stack GFG', 'Stack & Queue', 'Easy', 'https://www.geeksforgeeks.org/problems/get-minimum-element-from-stack/1', ARRAY['Amazon'], 'Stack'),
('Circular tour GFG', 'Stack & Queue', 'Medium', 'https://www.geeksforgeeks.org/problems/circular-tour-1587115620/1', ARRAY['Amazon'], 'Queue'),
('Next larger element GFG', 'Stack & Queue', 'Medium', 'https://www.geeksforgeeks.org/problems/next-larger-element-1587115620/1', ARRAY['Amazon'], 'Stack'),
('First non-repeating character in a stream GFG', 'Stack & Queue', 'Medium', 'https://www.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream1216/1', ARRAY['Amazon'], 'Queue'),
('Rotten Oranges GFG', 'Stack & Queue', 'Medium', 'https://www.geeksforgeeks.org/problems/rotten-oranges2536/1', ARRAY['Amazon'], 'BFS'),
('Stock span problem GFG', 'Stack & Queue', 'Easy', 'https://www.geeksforgeeks.org/problems/stock-span-problem-1587115621/1', ARRAY['Amazon'], 'Stack'),
('Maximum of all subarrays of size k GFG', 'Stack & Queue', 'Medium', 'https://www.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k3101/1', ARRAY['Amazon'], 'Deque'),

-- ============================================================
-- HEAP / PRIORITY QUEUE (20 problems)
-- ============================================================
('Find Median from Data Stream', 'Heap', 'Hard', 'https://leetcode.com/problems/find-median-from-data-stream/', ARRAY['Amazon','Google'], 'Heap'),
('Top K Frequent Words', 'Heap', 'Medium', 'https://leetcode.com/problems/top-k-frequent-words/', ARRAY['Amazon','Facebook'], 'Heap'),
('K Closest Points to Origin', 'Heap', 'Medium', 'https://leetcode.com/problems/k-closest-points-to-origin/', ARRAY['Amazon','Facebook','Google'], 'Heap'),
('Task Scheduler', 'Heap', 'Medium', 'https://leetcode.com/problems/task-scheduler/', ARRAY['Facebook','Amazon'], 'Heap'),
('Design Twitter', 'Heap', 'Medium', 'https://leetcode.com/problems/design-twitter/', ARRAY['Twitter'], 'Heap'),
('Reorganize String', 'Heap', 'Medium', 'https://leetcode.com/problems/reorganize-string/', ARRAY['Google'], 'Heap'),
('Smallest Range Covering Elements from K Lists', 'Heap', 'Hard', 'https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/', ARRAY['Google'], 'Heap'),
('Ugly Number II', 'Heap', 'Medium', 'https://leetcode.com/problems/ugly-number-ii/', ARRAY['Google'], 'Heap'),
('Super Ugly Number', 'Heap', 'Medium', 'https://leetcode.com/problems/super-ugly-number/', ARRAY['Amazon'], 'Heap'),
('Furthest Building You Can Reach', 'Heap', 'Medium', 'https://leetcode.com/problems/furthest-building-you-can-reach/', ARRAY['Amazon'], 'Heap'),
('Single-Threaded CPU', 'Heap', 'Medium', 'https://leetcode.com/problems/single-threaded-cpu/', ARRAY['Amazon'], 'Heap'),
('Maximum Performance of a Team', 'Heap', 'Hard', 'https://leetcode.com/problems/maximum-performance-of-a-team/', ARRAY['Google'], 'Heap'),
('IPO', 'Heap', 'Hard', 'https://leetcode.com/problems/ipo/', ARRAY['Google'], 'Heap'),
('Find K Pairs with Smallest Sums', 'Heap', 'Medium', 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/', ARRAY['Amazon'], 'Heap'),
('Kth Largest Element in a Stream', 'Heap', 'Easy', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', ARRAY['Amazon'], 'Heap'),
('Minimum Cost to Connect Sticks', 'Heap', 'Medium', 'https://leetcode.com/problems/minimum-cost-to-connect-sticks/', ARRAY['Amazon'], 'Heap'),
('Kth Smallest Element in a Sorted Matrix', 'Heap', 'Medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/', ARRAY['Google','Amazon'], 'Heap'),
('Heap Sort GFG', 'Heap', 'Medium', 'https://www.geeksforgeeks.org/problems/heap-sort/1', ARRAY['Amazon'], 'Heap'),
('K Largest Elements GFG', 'Heap', 'Medium', 'https://www.geeksforgeeks.org/problems/k-largest-elements4206/1', ARRAY['Amazon'], 'Heap'),
('Merge K Sorted Arrays GFG', 'Heap', 'Medium', 'https://www.geeksforgeeks.org/problems/merge-k-sorted-arrays/1', ARRAY['Amazon'], 'Heap'),

-- ============================================================
-- BINARY SEARCH (25 problems)
-- ============================================================
('Binary Search', 'Binary Search', 'Easy', 'https://leetcode.com/problems/binary-search/', ARRAY['Amazon','Microsoft'], 'Binary Search'),
('First Bad Version', 'Binary Search', 'Easy', 'https://leetcode.com/problems/first-bad-version/', ARRAY['Facebook'], 'Binary Search'),
('Search a 2D Matrix II', 'Binary Search', 'Medium', 'https://leetcode.com/problems/search-a-2d-matrix-ii/', ARRAY['Amazon','Microsoft'], 'Binary Search'),
('Find Peak Element', 'Binary Search', 'Medium', 'https://leetcode.com/problems/find-peak-element/', ARRAY['Google','Microsoft'], 'Binary Search'),
('Find First and Last Position of Element in Sorted Array', 'Binary Search', 'Medium', 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/', ARRAY['Amazon','Facebook'], 'Binary Search'),
('Search Insert Position', 'Binary Search', 'Easy', 'https://leetcode.com/problems/search-insert-position/', ARRAY['Amazon'], 'Binary Search'),
('Sqrt(x)', 'Binary Search', 'Easy', 'https://leetcode.com/problems/sqrtx/', ARRAY['Amazon','Microsoft'], 'Binary Search'),
('Guess Number Higher or Lower', 'Binary Search', 'Easy', 'https://leetcode.com/problems/guess-number-higher-or-lower/', ARRAY['Google'], 'Binary Search'),
('Koko Eating Bananas', 'Binary Search', 'Medium', 'https://leetcode.com/problems/koko-eating-bananas/', ARRAY['Amazon'], 'Binary Search'),
('Capacity To Ship Packages Within D Days', 'Binary Search', 'Medium', 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', ARRAY['Amazon'], 'Binary Search'),
('Split Array Largest Sum', 'Binary Search', 'Hard', 'https://leetcode.com/problems/split-array-largest-sum/', ARRAY['Facebook'], 'Binary Search'),
('Aggressive Cows GFG', 'Binary Search', 'Hard', 'https://www.geeksforgeeks.org/problems/aggressive-cows/1', ARRAY['Amazon'], 'Binary Search'),
('Book Allocation GFG', 'Binary Search', 'Hard', 'https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1', ARRAY['Amazon'], 'Binary Search'),
('Painter Partition Problem GFG', 'Binary Search', 'Hard', 'https://www.geeksforgeeks.org/problems/the-painters-partition-problem1535/1', ARRAY['Amazon'], 'Binary Search'),
('Median in a Row-Wise Sorted Matrix GFG', 'Binary Search', 'Hard', 'https://www.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1', ARRAY['Amazon'], 'Binary Search'),
('Floor in BST GFG', 'Binary Search', 'Easy', 'https://www.geeksforgeeks.org/problems/floor-in-bst/1', ARRAY['Amazon'], 'Binary Search'),
('Count Occurrences in Sorted Array GFG', 'Binary Search', 'Easy', 'https://www.geeksforgeeks.org/problems/number-of-occurrence2259/1', ARRAY['Amazon'], 'Binary Search'),
('Minimum Difference Element GFG', 'Binary Search', 'Easy', 'https://www.geeksforgeeks.org/problems/find-the-closest-number2223/1', ARRAY['Amazon'], 'Binary Search'),
('Peak Element GFG', 'Binary Search', 'Easy', 'https://www.geeksforgeeks.org/problems/peak-element/1', ARRAY['Amazon'], 'Binary Search'),
('Rotation Count GFG', 'Binary Search', 'Easy', 'https://www.geeksforgeeks.org/problems/rotation4723/1', ARRAY['Amazon'], 'Binary Search'),
('Find the Smallest Divisor Given a Threshold', 'Binary Search', 'Medium', 'https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/', ARRAY['Amazon'], 'Binary Search'),
('Minimize Max Distance to Gas Station', 'Binary Search', 'Hard', 'https://leetcode.com/problems/minimize-max-distance-to-gas-station/', ARRAY['Google'], 'Binary Search'),
('Random Pick with Weight', 'Binary Search', 'Medium', 'https://leetcode.com/problems/random-pick-with-weight/', ARRAY['Google','Facebook'], 'Binary Search'),
('Magnetic Force Between Two Balls', 'Binary Search', 'Medium', 'https://leetcode.com/problems/magnetic-force-between-two-balls/', ARRAY['Amazon'], 'Binary Search'),
('Maximum Value at a Given Index in a Bounded Array', 'Binary Search', 'Medium', 'https://leetcode.com/problems/maximum-value-at-a-given-index-in-a-bounded-array/', ARRAY['Google'], 'Binary Search'),

-- ============================================================
-- GREEDY (20 problems)
-- ============================================================
('Activity Selection GFG', 'Greedy', 'Medium', 'https://www.geeksforgeeks.org/problems/activity-selection-1587115620/1', ARRAY['Amazon'], 'Greedy'),
('Fractional Knapsack GFG2', 'Greedy', 'Medium', 'https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1', ARRAY['Amazon'], 'Greedy'),
('Job Sequencing Problem GFG', 'Greedy', 'Medium', 'https://www.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1', ARRAY['Amazon'], 'Greedy'),
('Huffman Encoding GFG', 'Greedy', 'Medium', 'https://www.geeksforgeeks.org/problems/huffman-encoding3345/1', ARRAY['Amazon'], 'Greedy'),
('Assign Cookies', 'Greedy', 'Easy', 'https://leetcode.com/problems/assign-cookies/', ARRAY['Amazon'], 'Greedy'),
('Lemonade Change', 'Greedy', 'Easy', 'https://leetcode.com/problems/lemonade-change/', ARRAY['Amazon'], 'Greedy'),
('Queue Reconstruction by Height', 'Greedy', 'Medium', 'https://leetcode.com/problems/queue-reconstruction-by-height/', ARRAY['Google'], 'Greedy'),
('Minimum Number of Arrows to Burst Balloons', 'Greedy', 'Medium', 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/', ARRAY['Microsoft','Amazon'], 'Greedy'),
('Partition Labels', 'Greedy', 'Medium', 'https://leetcode.com/problems/partition-labels/', ARRAY['Amazon','Facebook'], 'Greedy'),
('Bag of Tokens', 'Greedy', 'Medium', 'https://leetcode.com/problems/bag-of-tokens/', ARRAY['Google'], 'Greedy'),
('Largest Number', 'Greedy', 'Medium', 'https://leetcode.com/problems/largest-number/', ARRAY['Amazon'], 'Greedy'),
('Remove K Digits', 'Greedy', 'Medium', 'https://leetcode.com/problems/remove-k-digits/', ARRAY['Google'], 'Greedy'),
('Create Maximum Number', 'Greedy', 'Hard', 'https://leetcode.com/problems/create-maximum-number/', ARRAY['Google'], 'Greedy'),
('Monotone Increasing Digits', 'Greedy', 'Medium', 'https://leetcode.com/problems/monotone-increasing-digits/', ARRAY['Google'], 'Greedy'),
('Two City Scheduling', 'Greedy', 'Medium', 'https://leetcode.com/problems/two-city-scheduling/', ARRAY['Amazon'], 'Greedy'),
('Advantage Shuffle', 'Greedy', 'Medium', 'https://leetcode.com/problems/advantage-shuffle/', ARRAY['Google'], 'Greedy'),
('Minimum Domino Rotations For Equal Row', 'Greedy', 'Medium', 'https://leetcode.com/problems/minimum-domino-rotations-for-equal-row/', ARRAY['Google'], 'Greedy'),
('Hand of Straights', 'Greedy', 'Medium', 'https://leetcode.com/problems/hand-of-straights/', ARRAY['Facebook'], 'Greedy'),
('Boats to Save People', 'Greedy', 'Medium', 'https://leetcode.com/problems/boats-to-save-people/', ARRAY['Google'], 'Two Pointers'),
('Wiggle Subsequence', 'Greedy', 'Medium', 'https://leetcode.com/problems/wiggle-subsequence/', ARRAY['Google'], 'Greedy'),

-- ============================================================
-- BIT MANIPULATION (15 problems)
-- ============================================================
('Number of 1 Bits', 'Bit Manipulation', 'Easy', 'https://leetcode.com/problems/number-of-1-bits/', ARRAY['Microsoft','Apple'], 'Bit Manipulation'),
('Counting Bits', 'Bit Manipulation', 'Easy', 'https://leetcode.com/problems/counting-bits/', ARRAY['Amazon'], 'Dynamic Programming'),
('Reverse Bits', 'Bit Manipulation', 'Easy', 'https://leetcode.com/problems/reverse-bits/', ARRAY['Apple'], 'Bit Manipulation'),
('Missing Number LC', 'Bit Manipulation', 'Easy', 'https://leetcode.com/problems/missing-number/', ARRAY['Microsoft','Amazon'], 'Bit Manipulation'),
('Sum of Two Integers', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/sum-of-two-integers/', ARRAY['Amazon','Apple'], 'Bit Manipulation'),
('Single Number II', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/single-number-ii/', ARRAY['Amazon'], 'Bit Manipulation'),
('Single Number III', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/single-number-iii/', ARRAY['Amazon'], 'Bit Manipulation'),
('Power of Two', 'Bit Manipulation', 'Easy', 'https://leetcode.com/problems/power-of-two/', ARRAY['Amazon'], 'Bit Manipulation'),
('Bitwise AND of Numbers Range', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/bitwise-and-of-numbers-range/', ARRAY['Amazon'], 'Bit Manipulation'),
('Maximum XOR of Two Numbers in an Array', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/', ARRAY['Google'], 'Trie'),
('Find the Difference', 'Bit Manipulation', 'Easy', 'https://leetcode.com/problems/find-the-difference/', ARRAY['Amazon'], 'Bit Manipulation'),
('Subsets using Bit Manipulation', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/subsets/', ARRAY['Amazon'], 'Bit Manipulation'),
('Total Hamming Distance', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/total-hamming-distance/', ARRAY['Microsoft'], 'Bit Manipulation'),
('Gray Code', 'Bit Manipulation', 'Medium', 'https://leetcode.com/problems/gray-code/', ARRAY['Amazon'], 'Bit Manipulation'),
('Bit Difference GFG', 'Bit Manipulation', 'Easy', 'https://www.geeksforgeeks.org/problems/bit-difference-1587115620/1', ARRAY['Amazon'], 'Bit Manipulation'),

-- ============================================================
-- MATH & NUMBER THEORY (20 problems)
-- ============================================================
('Palindrome Number', 'Math', 'Easy', 'https://leetcode.com/problems/palindrome-number/', ARRAY['Amazon'], 'Math'),
('Happy Number', 'Math', 'Easy', 'https://leetcode.com/problems/happy-number/', ARRAY['Amazon'], 'Math'),
('Excel Sheet Column Number', 'Math', 'Easy', 'https://leetcode.com/problems/excel-sheet-column-number/', ARRAY['Microsoft'], 'Math'),
('Factorial Trailing Zeroes', 'Math', 'Medium', 'https://leetcode.com/problems/factorial-trailing-zeroes/', ARRAY['Amazon'], 'Math'),
('Reverse Integer', 'Math', 'Medium', 'https://leetcode.com/problems/reverse-integer/', ARRAY['Amazon','Microsoft'], 'Math'),
('Pow(x, n)', 'Math', 'Medium', 'https://leetcode.com/problems/powx-n/', ARRAY['Google','Facebook'], 'Binary Search'),
('Sqrt(x) Math', 'Math', 'Easy', 'https://leetcode.com/problems/sqrtx/', ARRAY['Amazon','Microsoft'], 'Binary Search'),
('Count Primes', 'Math', 'Medium', 'https://leetcode.com/problems/count-primes/', ARRAY['Amazon'], 'Math'),
('Roman to Integer LC', 'Math', 'Easy', 'https://leetcode.com/problems/roman-to-integer/', ARRAY['Amazon','Facebook'], 'Math'),
('GCD of Two Numbers GFG', 'Math', 'Easy', 'https://www.geeksforgeeks.org/problems/gcd-of-two-numbers3459/1', ARRAY['Amazon'], 'Math'),
('LCM And GCD GFG', 'Math', 'Easy', 'https://www.geeksforgeeks.org/problems/lcm-and-gcd4516/1', ARRAY['Amazon'], 'Math'),
('Sieve of Eratosthenes GFG', 'Math', 'Easy', 'https://www.geeksforgeeks.org/problems/sieve-of-eratosthenes5242/1', ARRAY['Amazon'], 'Math'),
('Prime Factorization GFG', 'Math', 'Easy', 'https://www.geeksforgeeks.org/problems/prime-factorization-using-sieve/1', ARRAY['Amazon'], 'Math'),
('Modular Exponentiation GFG', 'Math', 'Easy', 'https://www.geeksforgeeks.org/problems/modular-exponentiation-for-large-numbers5537/1', ARRAY['Amazon'], 'Math'),
('Modular Multiplicative Inverse GFG', 'Math', 'Medium', 'https://www.geeksforgeeks.org/problems/modular-multiplicative-inverse-1587115620/1', ARRAY['Amazon'], 'Math'),
('Find All Duplicates in an Array', 'Math', 'Medium', 'https://leetcode.com/problems/find-all-duplicates-in-an-array/', ARRAY['Amazon'], 'Math'),
('Excel Sheet Column Title', 'Math', 'Easy', 'https://leetcode.com/problems/excel-sheet-column-title/', ARRAY['Microsoft'], 'Math'),
('Number of Digit One', 'Math', 'Hard', 'https://leetcode.com/problems/number-of-digit-one/', ARRAY['Google'], 'Math'),
('Maximum Points You Can Obtain from Cards', 'Math', 'Medium', 'https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/', ARRAY['Amazon'], 'Sliding Window'),
('Ugly Number', 'Math', 'Easy', 'https://leetcode.com/problems/ugly-number/', ARRAY['Amazon'], 'Math'),

-- ============================================================
-- SORTING & SEARCHING (15 problems)
-- ============================================================
('Sort an Array', 'Sorting', 'Medium', 'https://leetcode.com/problems/sort-an-array/', ARRAY['Amazon'], 'Sorting'),
('Merge Sort GFG', 'Sorting', 'Medium', 'https://www.geeksforgeeks.org/problems/merge-sort/1', ARRAY['Amazon'], 'Divide and Conquer'),
('Quick Sort GFG', 'Sorting', 'Medium', 'https://www.geeksforgeeks.org/problems/quick-sort/1', ARRAY['Amazon'], 'Divide and Conquer'),
('Insertion Sort GFG', 'Sorting', 'Easy', 'https://www.geeksforgeeks.org/problems/insertion-sort/1', ARRAY['TCS'], 'Sorting'),
('Bubble Sort GFG', 'Sorting', 'Easy', 'https://www.geeksforgeeks.org/problems/bubble-sort/1', ARRAY['TCS'], 'Sorting'),
('Counting Sort GFG', 'Sorting', 'Easy', 'https://www.geeksforgeeks.org/problems/counting-sort/1', ARRAY['Amazon'], 'Sorting'),
('Radix Sort GFG', 'Sorting', 'Medium', 'https://www.geeksforgeeks.org/problems/radix-sort/1', ARRAY['Amazon'], 'Sorting'),
('Find H-Index', 'Sorting', 'Medium', 'https://leetcode.com/problems/h-index/', ARRAY['Facebook'], 'Sorting'),
('Minimum Absolute Difference', 'Sorting', 'Easy', 'https://leetcode.com/problems/minimum-absolute-difference/', ARRAY['Amazon'], 'Sorting'),
('Largest Perimeter Triangle', 'Sorting', 'Medium', 'https://leetcode.com/problems/largest-perimeter-triangle/', ARRAY['Google'], 'Greedy'),
('Array Partition', 'Sorting', 'Easy', 'https://leetcode.com/problems/array-partition/', ARRAY['Amazon'], 'Sorting'),
('Relative Sort Array', 'Sorting', 'Easy', 'https://leetcode.com/problems/relative-sort-array/', ARRAY['Google'], 'Sorting'),
('Maximum Gap', 'Sorting', 'Hard', 'https://leetcode.com/problems/maximum-gap/', ARRAY['Amazon'], 'Sorting'),
('Find Kth Largest XOR Coordinate Value', 'Sorting', 'Medium', 'https://leetcode.com/problems/find-kth-largest-xor-coordinate-value/', ARRAY['Google'], 'Heap'),
('Wiggle Sort II', 'Sorting', 'Medium', 'https://leetcode.com/problems/wiggle-sort-ii/', ARRAY['Google'], 'Sorting'),

-- ============================================================
-- HASHING (15 problems)
-- ============================================================
('Two Sum Hash', 'Hashing', 'Easy', 'https://leetcode.com/problems/two-sum/', ARRAY['Google','Amazon','Facebook','Apple','Microsoft'], 'Hashing'),
('First Unique Character in a String', 'Hashing', 'Easy', 'https://leetcode.com/problems/first-unique-character-in-a-string/', ARRAY['Amazon','Microsoft'], 'Hashing'),
('Contains Duplicate II', 'Hashing', 'Easy', 'https://leetcode.com/problems/contains-duplicate-ii/', ARRAY['Palantir'], 'Hashing'),
('Intersection of Two Arrays', 'Hashing', 'Easy', 'https://leetcode.com/problems/intersection-of-two-arrays/', ARRAY['Amazon'], 'Hashing'),
('Intersection of Two Arrays II', 'Hashing', 'Easy', 'https://leetcode.com/problems/intersection-of-two-arrays-ii/', ARRAY['Amazon','Facebook'], 'Hashing'),
('4Sum II', 'Hashing', 'Medium', 'https://leetcode.com/problems/4sum-ii/', ARRAY['Amazon'], 'Hashing'),
('Brick Wall', 'Hashing', 'Medium', 'https://leetcode.com/problems/brick-wall/', ARRAY['Facebook'], 'Hashing'),
('Number of Boomerangs', 'Hashing', 'Medium', 'https://leetcode.com/problems/number-of-boomerangs/', ARRAY['Google'], 'Hashing'),
('Longest Arithmetic Subsequence', 'Hashing', 'Medium', 'https://leetcode.com/problems/longest-arithmetic-subsequence/', ARRAY['Google'], 'Dynamic Programming'),
('Random Pick Index', 'Hashing', 'Medium', 'https://leetcode.com/problems/random-pick-index/', ARRAY['Facebook'], 'Hashing'),
('Jewels and Stones', 'Hashing', 'Easy', 'https://leetcode.com/problems/jewels-and-stones/', ARRAY['Amazon'], 'Hashing'),
('Uncommon Words from Two Sentences', 'Hashing', 'Easy', 'https://leetcode.com/problems/uncommon-words-from-two-sentences/', ARRAY['Google'], 'Hashing'),
('Subarray with given XOR GFG', 'Hashing', 'Medium', 'https://www.geeksforgeeks.org/problems/count-subarray-with-given-xor/1', ARRAY['Amazon'], 'Hashing'),
('Longest Subarray with Sum K GFG', 'Hashing', 'Medium', 'https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1', ARRAY['Amazon'], 'Hashing'),
('Count Distinct Elements in Every Window GFG', 'Hashing', 'Medium', 'https://www.geeksforgeeks.org/problems/count-distinct-elements-in-every-window/1', ARRAY['Amazon'], 'Sliding Window'),

-- ============================================================
-- DIVIDE AND CONQUER (10 problems)
-- ============================================================
('Merge Sort LC', 'Divide and Conquer', 'Medium', 'https://leetcode.com/problems/sort-an-array/', ARRAY['Amazon'], 'Divide and Conquer'),
('Binary Search DC', 'Divide and Conquer', 'Easy', 'https://leetcode.com/problems/binary-search/', ARRAY['Amazon'], 'Divide and Conquer'),
('Maximum Subarray DC', 'Divide and Conquer', 'Medium', 'https://leetcode.com/problems/maximum-subarray/', ARRAY['Amazon'], 'Divide and Conquer'),
('Pow(x,n) DC', 'Divide and Conquer', 'Medium', 'https://leetcode.com/problems/powx-n/', ARRAY['Google'], 'Divide and Conquer'),
('Different Ways to Add Parentheses', 'Divide and Conquer', 'Medium', 'https://leetcode.com/problems/different-ways-to-add-parentheses/', ARRAY['Google'], 'Divide and Conquer'),
('Find K-th Smallest Pair Distance', 'Divide and Conquer', 'Hard', 'https://leetcode.com/problems/find-k-th-smallest-pair-distance/', ARRAY['Google'], 'Binary Search'),
('Majority Element II', 'Divide and Conquer', 'Medium', 'https://leetcode.com/problems/majority-element-ii/', ARRAY['Amazon'], 'Divide and Conquer'),
('Number of Subarrays with Bounded Maximum', 'Divide and Conquer', 'Medium', 'https://leetcode.com/problems/number-of-subarrays-with-bounded-maximum/', ARRAY['Amazon'], 'Divide and Conquer'),
('Count of Range Sum', 'Divide and Conquer', 'Hard', 'https://leetcode.com/problems/count-of-range-sum/', ARRAY['Google'], 'Divide and Conquer'),
('Reverse Pairs', 'Divide and Conquer', 'Hard', 'https://leetcode.com/problems/reverse-pairs/', ARRAY['Amazon'], 'Merge Sort');
